---
version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=my_deltastream_postgres_user
      - POSTGRES_PASSWORD=my_deltastream_postgres_password
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
    volumes:
      - ~/deltastream/postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5532:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: deltastream@deltastream.com
      PGADMIN_DEFAULT_PASSWORD: deltastream_example_password
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    expose:
      - 80
      - 443
    depends_on:
      - postgres
