dbt_deltastream_example:
  outputs:
    dev:
      type: deltastream
      token: your-token-here

    prod:
      type: deltastream
      token: your-token-here
      database: prod # Optional
      schema: public # Optional
      #organization_id: your-organization-id-here # Optional
      #role: your-role-here # Optional
      #store: your-store-here # Optional

  target: dev
